version: "3.9"

services:
  browser-use-service:
    build: .
    container_name: browser-use-service
    env_file: .env
    ports:
      - "9010:9010"
    networks:
      - pioneerxity

networks:
  pioneerxity:
    external: true


